const ENUMS = {
	CAMERA_FOLLOW: 'follow',
	ORBIT_CONTROLS: 'controls',
  TEXTURE_MINECRAFT_TRAILER: 'texture-minecraft-trailer',
  TEXTURE_PLACEHOLDER: 'teaxture-placeholder'
}

export const TEXTURES = {
  GRASS: 'GRASS',
  GRASS_TOP: 'GRASS_TOP',
  COBBLESTONE: 'COBBLESTONE',
  GRAVEL: 'GRAVEL',
  SAND: 'SAND',
  DIRT: 'DIRT',
  STONE: 'STONE',
  GRANITE: 'GRANITE',
  SNOWY_GRASS: 'SNOWY_GRASS',
  QUESTION_MARK:'QUESTION_MARK',
  OBSIDIAN: 'OBSIDIAN',
  OAK_PLANKS: 'OAK_PLANKS',
  OAK_LOG: 'OAK_LOG',
  OAK_LOG_TOP: 'OAK_LOG_TOP',
  OAK_LEAVES: 'OAK_LEAVES',
  COAL_ORE: 'COAL_ORE',
  IRON_ORE: 'IRON_ORE',
  GOLD_ORE: 'GOLD_ORE',
  DIAMOND_ORE: 'DIAMOND_ORE',
}

export default ENUMS